### ISSUE TITLE
:player_join event fails

### ISSUE THREAD

**Issue by brandondrew** [enebo/Purugin#56]
a hello-world plugin works fine with Spigot, but a any plugin using the :player_join event fails like so:

~~~
[21:25:33 ERROR]: Could not pass event PlayerJoinEvent to Example v0.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit-1.8.8.jar:git-Bukkit-07c3001]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.8.8.jar:git-Bukkit-07c3001]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-1.8.8.jar:git-Bukkit-07c3001]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-1.8.8.jar:git-Bukkit-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:282) [craftbukkit-1.8.8.jar:git-Bukkit-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:142) [craftbukkit-1.8.8.jar:git-Bukkit-07c3001]
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:115) [craftbukkit-1.8.8.jar:git-Bukkit-07c3001]
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:53) [craftbukkit-1.8.8.jar:git-Bukkit-07c3001]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:222) [craftbukkit-1.8.8.jar:git-Bukkit-07c3001]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(SourceFile:168) [craftbukkit-1.8.8.jar:git-Bukkit-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:745) [craftbukkit-1.8.8.jar:git-Bukkit-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit-1.8.8.jar:git-Bukkit-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [craftbukkit-1.8.8.jar:git-Bukkit-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [craftbukkit-1.8.8.jar:git-Bukkit-07c3001]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `display_name' for #<Java::OrgBukkitEventPlayer::PlayerJoinEvent:0x736aa1a9>
	at RUBY.on_enable(/Users/brandon/Code/Spigot/plugins/example.rb:7) ~[?:?]
	at org.jruby.RubyProc.call(org/jruby/RubyProc.java:271) ~[?:?]
	at RUBY.on_event((eval):4) ~[?:?]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(SourceFile:168) ~[craftbukkit-1.8.8.jar:git-Bukkit-07c3001]
[21:25:33 INFO]: iconoclast[/127.0.0.1:65218] logged in with entity id 310 at ([world]-176.2323580778468, 81.05547480394029, -9.923850870811815)
~~~

The plugin code was taken from [the events wiki page](https://github.com/enebo/Purugin/wiki/Events):

~~~
class ExamplePlugin
  include Purugin::Plugin, Purugin::Colors
  description 'Example', 0.1

  def on_enable
    event(:player_join) do |s|
      server.broadcast_message yellow("#{s.display_name} has joined the game.")
    end
  end
end
~~~

I've tried starting up the minecraft server with both craftbukkit-1.8.8.jar and spigot-1.8.8.jar, and get similar results with both:

~~~
#!/bin/sh

cd "$( dirname "$0" )"
# GEM_HOME=./gems java -Xms1024M -Xmx1024M -jar spigot-1.8.8.jar
GEM_HOME=./gems java -Xms1024M -Xmx1024M -jar craftbukkit-1.8.8.jar
~~~

**Comment by brandondrew** [comment]
(You might notice that I was the last person who edited the Events wiki page: that was to remove an extra `end` and fix indentation.  Other than that the example code is unchanged.)

**Comment by enebo** [comment]
@brandondrew hmmm that looks bad :)  I will need to carve out some time to look into this because this was working the last time I worked on it (the variant of this is examples/motd.rb).  I am guessing no events are working atm?

**Comment by brandondrew** [comment]
None that I tried, which might have been only one or two others.  I can run through a larger sample and report back if that would be helpful.

**Comment by enebo** [comment]
I should have read this backtrace a bit more...Things do appear to be working but my example snippet on the wiki had another bug in it (now corrected on events page).  So two things:

1. The updated code:
    event(:player_join) do |s|
      server.broadcast_message yellow("#{s.player.display_name} has joined the game.")
    end
```ruby

The event has a getPlayer on it which has getDisplayName.  So whoops...but this leads to the second thing and something I will try and do a better job of in the not so distant future.

2. Less noisy error backtraces

```text
Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `display_name' for #<Java::OrgBukkitEventPlayer::PlayerJoinEvent:0x736aa1a9>
    at RUBY.on_enable(/Users/brandon/Code/Spigot/plugins/example.rb:7) ~[?:?]
```

So the real error was quite a bit lower in your submitted backtrace.  I need to extract that error so we get a much clearer error message on the console.
